config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, minimum: 5
  validates_presence_of :body
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), notice: "#{@comment.name} has been deleted"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice:  "You have created #{@post.title}"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
  if @post.update_attributes(post_params)
    redirect_to @post
  else
    render 'edit'
  end
  end


  def destroy
  if @post.destroy
    redirect_to posts_path
  else
    render 'edit'
  end
  end
  private

  def set_post
    @post= Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :body)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.clearfix
  .container
    %p
    %span.h4.alert-danger><= comment.name
    %p
    %strong.text-center.text-muted><= comment.body
    %p
    %span.alert-info><= time_ago_in_words(comment.created_at).concat(' ago')
    - if user_signed_in?
      = button_to( 'Delete_comments', [comment.post, comment],method: :delete,
      data: { confirm: 'Are you sure?', verify: 'Foo', verify_text: 'Type "Foo" to confirm' }, class: 'btn btn-lg btn-danger')

app/views/comments/_form.html.haml
= simple_form_for([@post,@post.comments.build]) do |f|
  = f.input :name
  %br
  = f.input :body
  %br
  = f.submit class: 'btn btn-success btn-sm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TumblrApp
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'


%body
  #sidebar
    %ul
      %li.category= link_to "Tumblr", root_path
      .btn-group-vertical.btn-group-justified
        = button_to 'Posts', root_path, method: :get, class: 'btn btn-success btn-sm btn-block'
        = button_to 'About', about_path, method:  :get, class: 'btn btn-warning btn-sm btn-block'
        - unless current_user
          = button_to  'User Login', new_user_session_path,method: :get, class: 'btn btn-primary btn-sm btn-block'

  #main_content
    #header
      - if current_page?(root_path)
        %p.h2 Post Feed
      - elsif current_page?(about_path)
        %p.h2 My site
      - else
        = link_to "Back to Post Feed", root_path, class: 'btn btn-sm btn-success'
      .btn-group.btn-group-sm.block-center.btn-group-vertical
        - if user_signed_in?
          = button_to('Make Post', new_post_url, method: :get, class: 'btn btn-lg bnt-default')
          = button_to(  'Log Out', destroy_user_session_path ,method: :delete, class: 'btn btn-lg btn-default')

    = bootstrap_flash

  .container
    = yield

app/views/pages/about.html.haml
.container
  .row.center-block
    .col-md-4.img-thumbnail.col-md-offset-4
      = image_tag 'profile.jpeg', class: 'img img-responsive'


    .row.pull-right
      .text-justify.label-primary.text-uppercase= h(                  |
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit."  + |
           "Aliquam lacinia nunc et tristique ultrices. Morbi aliquet arcu et lorem mattis," + |
           "fringilla gravida erat porttitor. Sed nulla velit, suscipit in finibus eget, ultricies at augue."  + |
           "Donec cursus pretium feugiat. Proin nec tristique massa. Nam sodales nisl dui,"  |
           "vitae ultricies neque aliquet in. Suspendisse ac velit dolor.") |

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  - if @post.errors.any?
    .alert.alert-danger
      %h2= pluralize(@post.errors.count, "error").concat(" stopped this pos from saving")
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %p
    = f.input :title
  %p
    = f.input :body
  %hr

  %p.col-md-4.center-block
    = f.submit class: 'btn btn-info  bnt-md'

app/views/posts/edit.html.haml
%h1 Make something New!

%hr
= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  #post_warpper
    %h2.title= link_to post.title, post
    %p.date= time_ago_in_words(post.created_at).concat(' ').concat('ago')
    %p.text-left= truncate(post.body, length: 80)
    

app/views/posts/new.html.haml
%h1 Make something New!

%hr

= render 'form'

app/views/posts/show.html.haml
#container
  %h1.title= @post.title

  %p.date= time_ago_in_words(@post.created_at).concat(' ').concat('ago')

  %p.body= @post.body

  %hr

  .btn-group-lg
    - if user_signed_in?
      = button_to( 'Edit post', edit_post_path(@post), method: :get, class: 'btn btn-lg btn-info')
      = button_to( 'Delete it', post_path, method: :delete, data: { confirm: 'Are you sure?'} ,class: 'btn btn-lg btn-danger' )
  .container
    %h2= @post.comments.count.to_s << ' Comments'
    = render @post.comments
    %h3 Join Discussion
    = render 'comments/form'